version: '3.9'

services:
  nest_micro_redis:
    image: redislabs/redismod
    container_name: nest_micro_redis
    ports:
      - 6380:6379
    command: /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/volumes/redis:/data
      - ./docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - nest_micro
  
  nest_micro_redisinsight:
    image: redislabs/redisinsight:latest
    container_name: nest_micro_redisinsight
    ports:
      - 8380:8001
    volumes:
      - ./docker/volumes/redisinsight:/db 

networks:
  nest_micro:
    driver: bridge

# volumes: