version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: nest_micro_redis
    ports:
      - 6380:6379
    command: redis-server --save 60 1 --requirepass 123456 --loglevel warning
    # Access command: redis-cli
    # For auth: auth 123456 (password as in --requirepass)
    networks:
      - nest_micro

networks:
  nest_micro:
    driver: bridge